name: Deploy to Vercel Free
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Vercel (Free Plan Auto)
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_xxxxxxxxxxxxxxx?buildCache=true"
